# Generated by Django 3.0.2 on 2020-02-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_book_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
